In [ ]:
x1=20
y1=30
x2=30
y2=40
##EUCLIDEAN
ed=((x2-x1)**2+(y2-y1)**2)**(1/2)
##Manhathan
md=abs((x2-x1))+abs((y2-y1))

print("ED:",ed,"MD:",md)

ED: 14.142135623730951 MD: 20

In [8]:
import pandas as pd
from collections import Counter

dic={
    'Name':['Aliyan','Ali','Mehak','Rafia','iftikhar','Umair','Sana','Waqaas','Sona','Ahmed'],
     'Age':[32,40,16,34,55,40,20,15,55,15],
     'Gender':['M','M','F','F','M','M','F','M','F','M'],
     'Class of sports':['Football','Neither','Cricket','Cricket','Neither','Cricket','Neither','Cricket','Football','Football']
}
df=pd.DataFrame(dic)
convert_dict = {'Gender': int}
 
# df = df.astype(convert_dict)
print(df.dtypes)

df['Gender']=df['Gender'].apply(lambda x: 1 if x=='M' else 0)
# df['Class of sports']=df['Class of sports'].apply(lambda x: 1 if x=='Cricket' else (lambda x:0.5 if x=='Football' else x==0))
display(df)
# x1,y1=df.iloc(df[0:'Age']),df.iloc(df[0:'Gender'])
print(x1,y1)
# for i in df:
#   ed1=((df-x1)**2+(y2-y1)**2)**(1/2)

# k=3
# K=int(input('Enter the K value : '))
# name='RIMSHA'
# Age=5
# Gender=0

# for i in df:
#   df['distance']=((Age-df['Age'])**2+(Gender-df['Gender']**2))**(1/2)


# df.sort_values(by=['distance'], inplace=True)


# index = pd.Index([1,2,3,4,5,6,7,8,9,10])
# df = df.set_index(index)

# result=[]
# result = df['Class of sports'].iloc[0:3].mode()
# if result.count() > 1 :
#   classOuput = result[0]
# else:
#   classOuput = result 

# print(name + "belong to " + classOuput + "Class")

Name               object
Age                 int64
Gender             object
Class of sports    object
dtype: object

       Name  Age  Gender Class of sports
0    Aliyan   32       1        Football
1       Ali   40       1         Neither
2     Mehak   16       0         Cricket
3     Rafia   34       0         Cricket
4  iftikhar   55       1         Neither
5     Umair   40       1         Cricket
6      Sana   20       0         Neither
7    Waqaas   15       1         Cricket
8      Sona   55       0        Football
9     Ahmed   15       1        Football

TypeError: ignored